version: '3'

services:
  api:
    build: ./Dockerfile.local
    container_name: api
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3308

  nginx:
    build: ./docker/nginx/Dockerfile
    ports:
      - 80:8080
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
